name: Lint Changed Files
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  buildAndTestForLinuxBasedPlatforms:
    name: Lint ${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
        run: dotnet format --verify-no-changes --verbosity diagnostic --include `git diff --name-only HEAD main`
